In [142]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
# ML--> knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler ,LabelEncoder

In [144]:
df = pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/datascience/data/student.csv')

In [145]:
df.shape

(395, 33)

In [146]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,higher education,higher education,at_home,teacher,...,very good,medium,high,very low,very low,good,6,5,6,6
1,GP,F,17,U,GT3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,excellent,medium,medium,very low,very low,good,4,5,5,6
2,GP,F,15,U,LE3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,very good,medium,low,low,medium,good,10,7,8,10
3,GP,F,15,U,GT3,T,higher education,5th to 9th grade,health,services,...,good,low,low,very low,very low,excellent,2,15,14,15
4,GP,F,16,U,GT3,T,secondary education,secondary education,other,other,...,very good,medium,low,very low,low,excellent,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,5th to 9th grade,5th to 9th grade,services,services,...,excellent,very high,high,high,very high,very good,11,9,9,9
391,MS,M,17,U,LE3,T,secondary education,primary education (4th grade),services,services,...,bad,high,very high,medium,high,bad,3,14,16,16
392,MS,M,21,R,GT3,T,primary education (4th grade),primary education (4th grade),other,other,...,excellent,very high,medium,medium,medium,good,3,10,8,7
393,MS,M,18,R,LE3,T,secondary education,5th to 9th grade,services,other,...,very good,high,very low,medium,high,excellent,0,11,12,10
394,MS,M,19,U,LE3,T,primary education (4th grade),primary education (4th grade),other,at_home,...,good,low,medium,medium,medium,excellent,5,8,9,9

In [147]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [148]:
df_sample = df[['Medu', 'Fedu','traveltime', 'studytime', 'failures', 'schoolsup', 'famsup',
    'activities','internet','famrel', 'freetime', 'goout', 'Dalc','Walc', 
    'health', 'absences', 'G1', 'G2', 'G3']]

In [149]:
df = df_sample

In [150]:
df.shape

(395, 19)

In [151]:
columnsdf = ['Medu', 'Fedu', 'traveltime', 'studytime','schoolsup',
       'famsup', 'activities', 'internet', 'famrel', 'freetime', 'goout',
       'Dalc', 'Walc', 'health']

In [133]:
for col in columnsdf:
    print(col)
    print('-'*50)
    unique =  df[col].unique()
    print(unique)
    print('-'*50)

Medu
--------------------------------------------------
['higher education' 'primary education (4th grade)' 'secondary education'
 '5th to 9th grade' 'none']
--------------------------------------------------
Fedu
--------------------------------------------------
['higher education' 'primary education (4th grade)' '5th to 9th grade'
 'secondary education' 'none']
--------------------------------------------------
traveltime
--------------------------------------------------
['15 to 30 min.' '<15 min.' '30 min. to 1 hour' '>1 hour']
--------------------------------------------------
studytime
--------------------------------------------------
['2 to 5 hours' '5 to 10 hours' '<2 hours' '>10 hours']
--------------------------------------------------
schoolsup
--------------------------------------------------
['yes' 'no']
--------------------------------------------------
famsup
--------------------------------------------------
['no' 'yes']
--------------------------------------------------
activities
--------------------------------------------------
['no' 'yes']
--------------------------------------------------
internet
--------------------------------------------------
['no' 'yes']
--------------------------------------------------
famrel
--------------------------------------------------
['very good' 'excellent' 'good' 'very bad' 'bad']
--------------------------------------------------
freetime
--------------------------------------------------
['medium' 'low' 'high' 'very low' 'very high']
--------------------------------------------------
goout
--------------------------------------------------
['high' 'medium' 'low' 'very low' 'very high']
--------------------------------------------------
Dalc
--------------------------------------------------
['very low' 'low' 'very high' 'medium' 'high']
--------------------------------------------------
Walc
--------------------------------------------------
['very low' 'medium' 'low' 'high' 'very high']
--------------------------------------------------
health
--------------------------------------------------
['good' 'excellent' 'very bad' 'bad' 'very good']
--------------------------------------------------

In [152]:
edu = {
'none':0,
'primary education (4th grade)': 1,
'secondary education':2,
'higher education':3,
'5th to 9th grade' :4
}
columns = ['Medu','Fedu']
for col in columns:
 df[col] = df[col].map(edu)

C:\Users\pinki\AppData\Local\Temp\ipykernel_11084\4213046110.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].map(edu)
C:\Users\pinki\AppData\Local\Temp\ipykernel_11084\4213046110.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].map(edu)

In [156]:
df.shape

(395, 19)

In [157]:
sf ={
    "yes" :1,
    "no" : 0
}

column =['schoolsup','famsup']
for col in column:
    df[col] = df[col].map(sf)

C:\Users\pinki\AppData\Local\Temp\ipykernel_11084\750724910.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].map(sf)
C:\Users\pinki\AppData\Local\Temp\ipykernel_11084\750724910.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].map(sf)

In [158]:
df

,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,activities,internet,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,3,3,15 to 30 min.,2 to 5 hours,0,NaN,NaN,no,no,very good,medium,high,very low,very low,good,6,5,6,6
1,1,1,<15 min.,2 to 5 hours,0,NaN,NaN,no,yes,excellent,medium,medium,very low,very low,good,4,5,5,6
2,1,1,<15 min.,2 to 5 hours,3,NaN,NaN,no,yes,very good,medium,low,low,medium,good,10,7,8,10
3,3,4,<15 min.,5 to 10 hours,0,NaN,NaN,yes,yes,good,low,low,very low,very low,excellent,2,15,14,15
4,2,2,<15 min.,2 to 5 hours,0,NaN,NaN,no,no,very good,medium,low,very low,low,excellent,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,4,4,<15 min.,2 to 5 hours,2,NaN,NaN,no,no,excellent,very high,high,high,very high,very good,11,9,9,9
391,2,1,15 to 30 min.,<2 hours,0,NaN,NaN,no,yes,bad,high,very high,medium,high,bad,3,14,16,16
392,1,1,<15 min.,<2 hours,3,NaN,NaN,no,no,excellent,very high,medium,medium,medium,good,3,10,8,7
393,2,4,30 min. to 1 hour,<2 hours,0,NaN,NaN,no,yes,very good,high,very low,medium,high,excellent,0,11,12,10
394,1,1,<15 min.,<2 hours,0,NaN,NaN,no,yes,good,low,medium,medium,medium,excellent,5,8,9,9

In [159]:
df['health'].unique()

array(['good', 'excellent', 'very bad', 'bad', 'very good'], dtype=object)

In [139]:
hlth = {
    0:'very good',
    1:'bad',
    2 :'good',
    3 :'very good',
    4:'excellent'
}
df['health'] = df['health'].map(hlth)

C:\Users\pinki\AppData\Local\Temp\ipykernel_11084\3710690070.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['health'] = df['health'].map(hlth)

In [140]:
df

,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,activities,internet,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,3,3,15 to 30 min.,2 to 5 hours,0,1,0,no,no,very good,medium,high,very low,very low,NaN,6,5,6,6
1,1,1,<15 min.,2 to 5 hours,0,0,1,no,yes,excellent,medium,medium,very low,very low,NaN,4,5,5,6
2,1,1,<15 min.,2 to 5 hours,3,1,0,no,yes,very good,medium,low,low,medium,NaN,10,7,8,10
3,3,4,<15 min.,5 to 10 hours,0,0,1,yes,yes,good,low,low,very low,very low,NaN,2,15,14,15
4,2,2,<15 min.,2 to 5 hours,0,0,1,no,no,very good,medium,low,very low,low,NaN,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,4,4,<15 min.,2 to 5 hours,2,0,1,no,no,excellent,very high,high,high,very high,NaN,11,9,9,9
391,2,1,15 to 30 min.,<2 hours,0,0,0,no,yes,bad,high,very high,medium,high,NaN,3,14,16,16
392,1,1,<15 min.,<2 hours,3,0,0,no,no,excellent,very high,medium,medium,medium,NaN,3,10,8,7
393,2,4,30 min. to 1 hour,<2 hours,0,0,0,no,yes,very good,high,very low,medium,high,NaN,0,11,12,10
394,1,1,<15 min.,<2 hours,0,0,0,no,yes,good,low,medium,medium,medium,NaN,5,8,9,9