In [98]:
import pandas as pd

In [99]:
df = pd.read_csv("C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/datascience_steps_daywise/cleaned_hr_data")

In [100]:
# groupby function,
# aggrigate function both are used
'''
-- if you perform analysis using aggrigate function then group by is not necessary
--if we perform analysis using group by then aggrigate function must be used
Aggrigate function
--------------------------
mean(),max(),min(),count()
kpi =(key performance indicator)
'''

'\n-- if you perform analysis using aggrigate function then group by is not necessary\n--if we perform analysis using group by then aggrigate function must be used\nAggrigate function\n--------------------------\nmean(),max(),min(),count()\nkpi =(key performance indicator)\n'

In [101]:
# find total number employee  by each gender
gender_count = df.groupby('Gender')['EmpID'].count().reset_index().rename(
    columns = {'EmpID':'Total Employees'}
)
gender_count

  Gender  Total Employees
0      F              354
1     M               228

In [102]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'F_Name', 'M_Name', 'L_Name'],
      dtype='object')

In [103]:
# find total salary
# Find total salary distributed to employee by each department. sum()

dep_count = df.groupby('Department')['Salary'].sum().reset_index().rename(
    columns = {'dep_name':'Total salary'}
)
dep_count

             Department    Salary
0         Admin Offices    646127
1      Executive Office    250000
2                 IT/IS   8134411
3     Production         26949336
4                 Sales   2140899
5  Software Engineering   4373364

In [104]:
dep_count = df.groupby('Department')['Salary'].sum().reset_index()
#stralign -> string align -> left right center
#numalign->number Align -> left right  center
print(dep_count.to_markdown(stralign='center', numalign='left'))

|    |      Department      | Salary   |
|:---|:--------------------:|:---------|
| 0  |    Admin Offices     | 646127   |
| 1  |   Executive Office   | 250000   |
| 2  |        IT/IS         | 8134411  |
| 3  |      Production      | 26949336 |
| 4  |        Sales         | 2140899  |
| 5  | Software Engineering | 4373364  |

In [105]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'F_Name', 'M_Name', 'L_Name'],
      dtype='object')

In [106]:
department_details = df.groupby('Department').agg(
    total_salary = ('Salary','sum'),
    total_employee = ('DeptID','sum')

).reset_index()


department_details

             Department  total_salary  total_employee
0         Admin Offices        646127               9
1      Executive Office        250000               2
2                 IT/IS       8134411             246
3     Production             26949336            2096
4                 Sales       2140899             186
5  Software Engineering       4373364             157

In [107]:
# Print report of an analysis where total salary, total employees, average employee satisfaction,
# total absence days of emplyoees by each department.
# agg() -> aggregate function


dep_details = df.groupby('Department').agg(
    Total_salary = ('Salary','sum'),
    Total_employee = ('EmpID','sum'),
    Avg_emp_satisfaction =("EmpSatisfaction","sum"),
    Total_absence = ("Absences","sum")

).reset_index()
dep_details

,Department,Total_salary,Total_employee,Avg_emp_satisfaction,Total_absence
0,Admin Offices,646127,91092,32,78
1,Executive Office,250000,10089,3,10
2,IT/IS,8134411,830482,298,1048
3,Production,26949336,4240006,1676,3914
4,Sales,2140899,315535,125,358
5,Software Engineering,4373364,406998,132,647

In [108]:
# abs_data = dep_details['Total_Absence'] < 100
# dep_details[abs_data]
dep_details

,Department,Total_salary,Total_employee,Avg_emp_satisfaction,Total_absence
0,Admin Offices,646127,91092,32,78
1,Executive Office,250000,10089,3,10
2,IT/IS,8134411,830482,298,1048
3,Production,26949336,4240006,1676,3914
4,Sales,2140899,315535,125,358
5,Software Engineering,4373364,406998,132,647

In [109]:
dep_details = df.groupby('Department').agg(
    Total_salary = ('Salary','sum'),
    Total_employee = ('EmpID','sum'),
    Avg_emp_satisfaction =("EmpSatisfaction","sum"),
    Total_absence = ("Absences","sum")

).sort_values(ascending= True, by = 'Total_salary').reset_index()

dep_details['Tota_salary'] = dep_details['Total_salary'].map("rs.{:,.2f}".format)
dep_details['Avg_emp_satisfaction'] = dep_details['Avg_emp_satisfaction'].map("rs.{:,.2f}".format)
dep_details

,Department,Total_salary,Total_employee,Avg_emp_satisfaction,Total_absence,Tota_salary
0,Executive Office,250000,10089,rs.3.00,10,"rs.250,000.00"
1,Admin Offices,646127,91092,rs.32.00,78,"rs.646,127.00"
2,Sales,2140899,315535,rs.125.00,358,"rs.2,140,899.00"
3,Software Engineering,4373364,406998,rs.132.00,647,"rs.4,373,364.00"
4,IT/IS,8134411,830482,rs.298.00,1048,"rs.8,134,411.00"
5,Production,26949336,4240006,"rs.1,676.00",3914,"rs.26,949,336.00"

In [110]:
# Find total employees data by each department and its performance score.
total_employee = df.groupby(['Department','PerformanceScore'])['EmpID'].count().reset_index()
total_employee

              Department   PerformanceScore  EmpID
0          Admin Offices        Fully Meets      9
1       Executive Office        Fully Meets      1
2                  IT/IS            Exceeds      7
3                  IT/IS        Fully Meets     73
4                  IT/IS  Needs Improvement      1
5                  IT/IS                PIP      1
6      Production                   Exceeds     86
7      Production               Fully Meets    310
8      Production         Needs Improvement     15
9      Production                       PIP      8
10                 Sales            Exceeds      2
11                 Sales        Fully Meets     24
12                 Sales  Needs Improvement      1
13                 Sales                PIP      4
14  Software Engineering            Exceeds      2
15  Software Engineering        Fully Meets     37
16  Software Engineering  Needs Improvement      1

In [111]:
# find total Employees data by each department and performance score 
dep_perf = df.groupby(['Department','PerformanceScore'])['EmpID'].count().reset_index()
dep_filter = (dep_perf['PerformanceScore']=='Fully Meets')|(dep_perf['PerformanceScore']=='Exceeds')
dep_perf[dep_filter]

              Department PerformanceScore  EmpID
0          Admin Offices      Fully Meets      9
1       Executive Office      Fully Meets      1
2                  IT/IS          Exceeds      7
3                  IT/IS      Fully Meets     73
6      Production                 Exceeds     86
7      Production             Fully Meets    310
10                 Sales          Exceeds      2
11                 Sales      Fully Meets     24
14  Software Engineering          Exceeds      2
15  Software Engineering      Fully Meets     37

In [112]:
## find total Employees data by each department and performance score 
# same problem by using isin function
dep_filter = dep_perf['PerformanceScore'].isin(['Fully Meets','Exceeds'])
dep_perf[dep_filter]

              Department PerformanceScore  EmpID
0          Admin Offices      Fully Meets      9
1       Executive Office      Fully Meets      1
2                  IT/IS          Exceeds      7
3                  IT/IS      Fully Meets     73
6      Production                 Exceeds     86
7      Production             Fully Meets    310
10                 Sales          Exceeds      2
11                 Sales      Fully Meets     24
14  Software Engineering          Exceeds      2
15  Software Engineering      Fully Meets     37

In [113]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,F_Name,M_Name,L_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,Sidi,Karthikeyan,Ait
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,Sarah,NaN,Akinkuolie
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Carol,NaN,Anderson
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,Linda,NaN,Anderson
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,Colby,NaN,Andreola
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,Sam,NaN,Athwal
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,Linda,NaN,Bachiochi

In [114]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'F_Name', 'M_Name', 'L_Name'],
      dtype='object')

In [115]:

df['DateofHire'] = pd.to_datetime(df['DateofHire'])

In [116]:
df['Hire_Year'] = df['DateofHire'].dt.year
df['Hire_Month_name'] = df['DateofHire'].dt.month_name()
df['Hire_Day_name'] = df['DateofHire'].dt.day_name()

In [117]:
df['Hire_Day_name'].unique()

array(['Tuesday', 'Monday', 'Thursday', 'Wednesday', 'Sunday', 'Friday',
       'Saturday'], dtype=object)

In [118]:
weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
# Categorical -> pandas
df['Hire_Day_name'] = pd.Categorical(df['Hire_Day_name'], categories=weekdays)
df['Hire_Day_name']

0      Tuesday
1       Monday
2      Tuesday
3       Monday
4       Monday
        ...
577     Monday
578     Monday
579     Monday
580     Monday
581     Monday
Name: Hire_Day_name, Length: 582, dtype: category
Categories (7, object): ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [119]:
# Find total employees hired in each day.
hire_day = df.groupby('Hire_Day_name', observed=False)['EmpID'].count().reset_index()
hire_day

  Hire_Day_name  EmpID
0        Sunday      6
1        Monday    471
2       Tuesday     77
3     Wednesday      9
4      Thursday     10
5        Friday      6
6      Saturday      3